include:
  - template: Jobs/SAST.gitlab-ci.yml

cache:
  paths:
    - .m2/repository
    - node_modules/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build-backend
  - test-backend
  - package-backend
  - release-backend
  - security

# Backend Jobs
build-backend:
  stage: build-backend
  image: maven:3.9-eclipse-temurin-20
  script:
    - "echo 'Starting Backend Build Stage'"
    - "mvn compile -f studytrade-backend/pom.xml"
  only:
    - develop

test-backend:
  stage: test-backend
  image: maven:3.9-eclipse-temurin-20
  script:
    - "echo 'Starting Backend Test Stage'"
    - "mvn test -Dtest='de.studytrade.studytradebackend.controller.ProductControllerTest,de.studytrade.studytradebackend.StudytradeBackendApplicationTests' -f studytrade-backend/pom.xml"
  artifacts:
    reports:
      junit:
        - studytrade-backend/target/surefire-reports/TEST-*.xml
        - studytrade-backend/target/failsafe-reports/TEST-*.xml
  only:
    - develop

package-backend:
  stage: package-backend
  image: maven:3.9-eclipse-temurin-20
  script:
    - "echo 'Starting Backend Package Stage'"
    - "mvn package -Dtest='de.studytrade.studytradebackend.controller.ProductControllerTest,de.studytrade.studytradebackend.StudytradeBackendApplicationTests' -f studytrade-backend/pom.xml"
  only:
    - develop
  artifacts:
    paths:
      - studytrade-backend/target/*.jar
    expire_in: 2 days

release-backend-container-latest:
  stage: release-backend
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/studytrade-backend"
      --dockerfile "${CI_PROJECT_DIR}/studytrade-backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  only:
    - develop

release-backend-container-tag:
  stage: release-backend
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/studytrade-backend"
      --dockerfile "${CI_PROJECT_DIR}/studytrade-backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  rules:
    - if: "$CI_COMMIT_TAG"
    - if: '$CI_COMMIT_REF_NAME == "develop"'

  # SAST Job
sast:
  stage: security
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
  # Inherit settings from the SAST template
